profiles:
    git:
        account1:
            name: ENC[AES256_GCM,data:l1OKGr03sOKoEHP0+w==,iv:fpo12kWUzPqJTvo0xUEqIGgjrvJQSF7IuS7hBhPVzGA=,tag:T38qU+ZrV7iUAoP7Ti8csw==,type:str]
            email: ENC[AES256_GCM,data:tKUtWdZNkQjPGzaryeG9oN6FjBk=,iv:owpWplysss5Xp8vOyDcNINEVQvIO/YrR6CSOGEsnBIg=,tag:LHL8fWmSBQgptpqHvx7IuQ==,type:str]
            directories:
                - ENC[AES256_GCM,data:FMaYOFVEl5mkpG8=,iv:aca3Danla0MoBMejPsM1pH7+mRVHFIHEYJs9ZdaoUdk=,tag:GcmyJaMNPMXfp9JMcEwWIw==,type:str]
                - ENC[AES256_GCM,data:4emy/p3RQM5n8g==,iv:zm//qzple+r1Cd36ZjjpTE6eYI+nZDZeYFRBwNSEYS8=,tag:H2lAO5/LeQSx2p/vfKEQHg==,type:str]
            ssh-key: ENC[AES256_GCM,data:ZtrVwgWZOLJ6RiBGSghwssxDvuayvIc=,iv:Werm6DyqoL/Bd8fdPyY9jdlO/AIE1jJkVjf1yvKEUBU=,tag:AlIDKCa/y4oEk6Oj9HN7Cg==,type:str]
        account2:
            name: ENC[AES256_GCM,data:iU3xF7/3nGqs,iv:UboJI3rdp8yjwGUniL1Xx8AGg/mqO2w/bKDFspnitxw=,tag:Mf605yTaE5hSZr2LnUa5wA==,type:str]
            email: ENC[AES256_GCM,data:c90mR61NxYhLIlyWnNIR9dn5NQ==,iv:bvhHS4tbI98KYHouvk22ym7TrynZNVI/1LmVEbrYDuI=,tag:HPc+7C+dS7Jh0xp8Ng9/oA==,type:str]
            directories:
                - ENC[AES256_GCM,data:aVtKpIiG7i6L6eE=,iv:Q20z+nTitpRdkeaUkZOf/JntI0LdNPXOGcDRwe3TOng=,tag:QJyBHvgfJMdum0/SckndWw==,type:str]
            ssh-key: ENC[AES256_GCM,data:ysjK4NACM0kBcFwLLodqLFpAOkVpLeM=,iv:H2SOXx34fMeZN0EO3Yke8aXfbRKWeVA8gDW7rm6wv0w=,tag:IFJ+8MZG/xHCNLltKUQUFQ==,type:str]
#ENC[AES256_GCM,data:NZxjcC3e5x4StRsxwGk=,iv:LvSVXMTxFqxS56w8U5FETGl5F3xRVMlxiAVUygK/eko=,tag:CjAk3Fg8EkSHpSMgRZUdHg==,type:comment]
forgejo:
    domain: ENC[AES256_GCM,data:iDwBJ77olGFvcbpFTbXYx2rNHQ0=,iv:BY/eFpzJ/74IYSeNylSod0tggXZtlzLxf0UZv5ElXpc=,tag:vbbzBRmUye4MWAwtXKXVxw==,type:str]
    tunnel-id: ENC[AES256_GCM,data:hirod+hdRyyxh22XrJ7/ubBksgE9qTht00/KcIPZxPdZF8MP,iv:amEYL8JI1lSkBhWPxM8OqVuvsSzF8DhknbHrFm8rs0Y=,tag:xkjqt2h/V7/xQm+mLur1NA==,type:str]
    #ENC[AES256_GCM,data:NSIMnBrWRxu6xD9sQxjM/eN68uuMZQtrMsnXYNYHw0UG94FWS27vMZhsHSii/V9gNgi79LUVZyfjuiXbezvL0NsrMQ==,iv:3OOl6Ue/9odUk8KaEEgMDJTmfibBYnOUmiFrtAStPrY=,tag:soQaHc0Jqk0E72ZDPV4tUA==,type:comment]
    #ENC[AES256_GCM,data://hsCyT/RCwaiAtjNVnudV2FhgqKDuzbieraH/fwOqiG+Glh0omLmro=,iv:TPvG0/P1hNuLs98lcrUKh/i3y5n95Oj1k3dniqn3mtw=,tag:vbZP2e19tQwsScX/+MWHLg==,type:comment]
    #ENC[AES256_GCM,data:tdb41CXPE2726wFK9aCwcN2FUfEK/4RQzKdOKuuvg45NbJTPPFM7eou89RjBLEWWhhZ1Lw==,iv:OK/ZXEXR2o7Y4X/l77aveqUBDo7qEfjVjCW8qoGCbr8=,tag:Zbag/VKVVZhl46b3PW0xHw==,type:comment]
    #ENC[AES256_GCM,data:2dm+IP96XNETwDxnKz0C4360UGeseR4Dx/AMADOvPIqAVs2lujwTj/TtLU5LSUH32O1+OeDhire7leoKFi7CYVU=,iv:YvNdmW9KAH/A3HOJ/7A0kfkYuzvmf6c2EBJOs2p4ugY=,tag:l3ojOxzxJcDTvcEzkzJFMg==,type:comment]
    #ENC[AES256_GCM,data:1t5Ebe9CRAP4/R8iOlXyimNlDoSv,iv:O9uNSI4nAQYuwAJ2jStA46LtS0Cg+VrGVNsKKBH6sgA=,tag:JLOOasTKU6JiFLyGkCT45w==,type:comment]
    turnstile-sitekey: ENC[AES256_GCM,data:o/BaJGNHO7NNVO7fio/moTb4HQmhz3ov,iv:OW7/8WQi0RLL8eYoRKu7Dd3gH1VOJgn/2mk0ErBkAcc=,tag:Qpf8Xz6SVjvLYG87Qf12Ag==,type:str]
    turnstile-secret: ENC[AES256_GCM,data:F4tZOVLMXbLhSLWfcobzdQSYqRmS394TR3T+wDiPO0HOhmk=,iv:6h1p7zbm42+Nd4NlY219dqBJtWkIyL5/2WQbtn1WlAQ=,tag:UXUYOS9cGF80IQ7oOP+TDA==,type:str]
    runner-token: ENC[AES256_GCM,data:xriNavh7T8D4VK8vx+vkxFFJFt5OrCjQUqv7fgYFkHKTjKA4I+MrpyUqAg==,iv:Zw6abT5fDYQcdnF5bzXFGjna11dHZyief83BbeUc6hI=,tag:XlxdtC3nGVU8bVAli/2VQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMm9aZHNYTTZvaGRXK3Nj
            ZzJBYnhRUTlpbjkyUW02WGtvcWlYVXRxY0VjCmRhSHAybmQ5MjlFRlNhZmQ3dzZa
            UnF0NENvb0wwWm9TNDh0Y1k5cE5sYWMKLS0tIE5wRzd6RlNSZ1ZrWWd6MTEvUjBt
            ZVdmNmVDdzJYeVc3SDhUZFczZjViNjAKC6YLFFfDdDCVWZiwTbPpc4vVSVz7EhU+
            ZhKOb41c7CtgqmexZijbg/R4r+QHuRqojpl+34MPdWS4ZUdb91k+kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm3vp7zd2mvjz07mtlx32yta56pv52yhm7ujw9us5sqszq84nvws2ec4n3
    lastmodified: "2026-07-13T00:19:15Z"
    mac: ENC[AES256_GCM,data:Ru78MkZZslWN6JribcpCeYYX5XCdleeDxjo5Kbuakg5hBcniyxHbkMfvEwdhihEVlhet5yayPpCLdsbq6++nBzex+cWTCqQTvTBjkPsblysLuubEgy3mb1r8sRdkMLjKSUq6wOHutipbJfwbgx3A3A64dR3vQ2r8QLwg1h36r5E=,iv:MCok9QRVP3Bve/TRjol+mbEChogyyCHqf7hsVMfoGSU=,tag:/0a14y4bhgISurnxZCUvkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
