profiles:
  git:
    account1:
      name: username1
      email: username1@email.com
      directories: ["~/username1", "/etc/nixos"]
      ssh-key: "~/.ssh/github.username1"
    account2:
      name: username2
      email: username2@email.com
      directories: ["~/username2"]
      ssh-key: "~/.ssh/github.username2"