profiles:
    git:
        account1:
            name: ENC[AES256_GCM,data:UBYvFg+JgNdhn11ODw==,iv:xUzlXcv5Et+h3dEItfwCI1NWgDrc3Cgm2NwtAqXSvTg=,tag:9aCU8f8vankAOn1RxkyI4w==,type:str]
            email: ENC[AES256_GCM,data:XQSueITl45eHe203JL40g9Ujo9k=,iv:+5OneEiiAR3JHRCtI0VqGkwnuMO6f5wfJWOJOpzQxYQ=,tag:iWcp4gGFrWKEws1zaM7zSw==,type:str]
            directories:
                - ENC[AES256_GCM,data:sxwvDjxToaxMQQI=,iv:t3qaZSQdIQKxOIQRvAj0TMD7VPGTShBgtQ2Sx89R72s=,tag:7dnml7tkfOh0ng/keC4BdQ==,type:str]
                - ENC[AES256_GCM,data:4ONf9kRU2QkNhA==,iv:97MfSMoOkrqV3K2uADjytqSBywKzUL8rpLTPWhVQXnk=,tag:/N6RJ8F5KMzzAPyHszFjeA==,type:str]
            ssh-key: ENC[AES256_GCM,data:y5zUgkEldG7DN3mt5penrJzpm9Byw9g=,iv:0N7+ZHjXKuKLskkSMissRvDVWUq08VT09DU/YQ6kT1c=,tag:H7dOl9RT0PLSXOr2+XwMiA==,type:str]
        account2:
            name: ENC[AES256_GCM,data:NEmRwIN9quq6,iv:w0Ts2/JebuGsZ/JiBs//d7VuyxIEaByrnexleAZlrQg=,tag:WGuHAbFtt6W3m5BkU/KxsQ==,type:str]
            email: ENC[AES256_GCM,data:VlJCE6T0a/tP/SB7Db/hMGJOUQ==,iv:HBqWEDB9mvMwC7F2AR3L1QdiBNL0hf3ceAvAFXqfmXM=,tag:pk9YKZvd204vbvNgtXbrtw==,type:str]
            directories:
                - ENC[AES256_GCM,data:jPsTHz+Ghvr7cC0=,iv:L2nGg9pm3AcS3y0HVx5oDf9kTj8Xf6/CFKwdu8mJ5Hg=,tag:mYgQ5X390jnamP8pkrsg1A==,type:str]
            ssh-key: ENC[AES256_GCM,data:w8kZ9sCvOiFBLpf4PUcBq/g8xx2X5is=,iv:1g2KlmFnuA2wa7NyiR5wQ6w4gCAtNkW9i6c7y0lpNpQ=,tag:wAekhiBTpXiEzqZPzY2bcQ==,type:str]
forgejo:
    domain: ENC[AES256_GCM,data:HFmEw4E7WUy7DsLsW2J0CuryPIU=,iv:+pJ+POPc5P2hdrZwK/kXPC8weLGgdkV8O/EU3Q+46Xo=,tag:freX7SejglCZETQ6kSosNQ==,type:str]
    tunnel-id: ENC[AES256_GCM,data:OM4669fBVglYm7OqNcKvYlQ9sNv1JtYtJWHiq483s/7x2n9a,iv:PJXxcZCFCb1/C4osH4ck3hVnJvHREPNZhlM2XLprZ1A=,tag:lnMgmTvXPiqSTxUNlxn+vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TUJCSzRGdnphN0JBSml5
            UUhWelNXbWhzcWRLWkM5UTVmdGpxUVhZSUM4CklZYnRGWjZMeDl4RGVPL3F3YitG
            LzhuWGpJOHBTNUc4d3E4NU1Md0JGUW8KLS0tIGQyWmtYRlk0RmtudFlhcmZUVnJz
            TzcyZjl2ektrTkkyb1FkQkhLdXpSSGsKOFgclIFmN6DPP80iqzOfONRWzaLuvaza
            rZ8laXuug5rHFCXzdSiucjF8MEDbEfJnteLamSaUxIty50Zcqodfkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm3vp7zd2mvjz07mtlx32yta56pv52yhm7ujw9us5sqszq84nvws2ec4n3
    lastmodified: "2026-07-12T22:12:16Z"
    mac: ENC[AES256_GCM,data:QLfEqOHjMzsl1w/QJpffHwykjJKyZT3iyPbIMQQzvYYq5U4mXvUkEvyuPOCdSNxsgksMBTbr+Yq/oMA4t2bUUu8BjC7fqwRDFvA+FFCc91yqXpFxMlVwt4ORl8ch8bVLV5Zohop9bL/hbGGsn29UvmjWNknZGggAXAKBw7jBWAo=,iv:qzh0AcYf3PqdwHmEJkwjLkF0O5ZH1LTuGBeieuFkqss=,tag:wMdKfWzFsMbOZXO67j9ZKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
