profiles:
    git:
        account1:
            name: ENC[AES256_GCM,data:D+8agN4p8suCXb9iQw==,iv:p3t6NZu3t2ZpgoLWnqut0C0VN1VXlOzF0986NXSSA0A=,tag:7FDjMLg7IWRetWEKuVnEfA==,type:str]
            email: ENC[AES256_GCM,data:TLToOtJV2QRPmFQdeAii+entztc=,iv:M2QYQJi+l1whW87sw6mtl35PELHW8QXSXucO7rlNKT8=,tag:9rJMzbPWmeDcC64y98hZEg==,type:str]
            directories:
                - ENC[AES256_GCM,data:4GAMxxlbEw7uRAQ=,iv:/1ca7hrp0/uQPSeN9ZNm7s1x8vWvMGs1SCPHmvvQ7zc=,tag:1ih7Tdoo+498bpMCQ2ANTw==,type:str]
                - ENC[AES256_GCM,data:OpgTe4hIOSEQcg==,iv:hv+N9P4pGtU3V3zxgHeGFRBZTgFRigffAqby2L9y11w=,tag:JJ+ZzeZVn9dcA7SpNvChTg==,type:str]
            ssh-key: ENC[AES256_GCM,data:G8qLYJQK6oJsRAC8i7wSE110vIhJXrc=,iv:yP0xlJh8DLHLbGhOBFLAqt18aw1MPPrAmF5CJzQp+lU=,tag:jg9mMllPYcIen7HOlbbkhQ==,type:str]
        account2:
            name: ENC[AES256_GCM,data:r25yf9BCJm35,iv:iKUlckf3Amz79chWft105z3gfLHcFRWR/Crfwj7kd+U=,tag:dzJlXY5Ht+wr5Qfv2/hg0Q==,type:str]
            email: ENC[AES256_GCM,data:PFoiJSSeMXvfwqpicgkyHsrMAw==,iv:QgQvNWxDaZsFYDJHBU/TcaxiG/MaUHEi2c9z/Yf5xh8=,tag:ELruk9VWsNBEWQeIRUUchA==,type:str]
            directories:
                - ENC[AES256_GCM,data:ImaRre8/TVI2uQA=,iv:zq/hhtKGPvZJ7A5jtXFOF0Dl2J7/q2w6H9fAcwqcqjQ=,tag:l1RcIwsqz7vwL1nkTTfQeg==,type:str]
            ssh-key: ENC[AES256_GCM,data:4nQLOlIDRI9WlnH5V5atRlN4BOWCT50=,iv:HpGmIwrNDU7O0gzOXnrtaK+bMCfgpoIacYxs5J1+No4=,tag:Mz9ybORUAvkUQMAg/sCsAA==,type:str]
    forgejo:
        domain: ENC[AES256_GCM,data:Pyt0Buecrl5GRGm3hzpJPZdrpXw=,iv:rkJ3e2P//1L+LwO7cnD8gxxqw0HTJdyUBxKa8dGrYVs=,tag:KV+kmxBb+jFZOOYrRGB4Mg==,type:str]
        tunnel-id: ENC[AES256_GCM,data:L28f4haLjC+lPGzcznPsO2yGpHDQ9DCquaTrsjTKrVBQ2yjS,iv:Pq98NuMK7CvyeDjyD+R9aYEB8C+6+kTonczZ1MuA4RM=,tag:1M1GNhcApW30OxYjx18i2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGhKeElSQVg1blJjOFlF
            WHNnQ29lUGlMUEFYOTUrVXVOOGwwd09JOEQwCnFYSmpQMTFjRnZsc2JGd2N1aFdl
            NmN3QXp6QTdGL3lKOUVWRnUrTjBVZHcKLS0tIGQyeEM5QitMem9lNUQzT2JYRDdp
            RW9WbDVSRldNU1dnZE9ya2tWVVVLNzAKY+D7nNPTGwG/7c9INuCZHgnT/3oHtxG5
            AE4rP1ICDogOIDMTrozvCvixjz3IFSwqxorSJBZQphEEMu5Ry2DDCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm3vp7zd2mvjz07mtlx32yta56pv52yhm7ujw9us5sqszq84nvws2ec4n3
    lastmodified: "2026-07-12T22:43:09Z"
    mac: ENC[AES256_GCM,data:Xtsve/0mikR1dFm9EUPhZnQUA/JAqKoRhE/2CfbeirC05psZeTSyds/Y1N9rNJ9xVP4vhDcrJqmki7c6CWfSLpVoCIEYgcKBURxM83FAL3GGWdGedwGnx/ViyakOkclgkK3WfHfl52BMf+IxONNGymJWncT7uHQLe6tCRvB3cIs=,iv:aaHp6WMC5vdxN3+G6Pob/QQzeBrZPKccy8R+nb+QGes=,tag:qRg/hGBpDy3pqjil64eTSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
