# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-09881e92-72a3-47ff-b56b-3b769a98646d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-09881e92-72a3-47ff-b56b-3b769a98646d".device = "/dev/disk/by-uuid/09881e92-72a3-47ff-b56b-3b769a98646d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C1C7-87F4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6bdc6981-2a81-4c1e-950c-77ef270f6ad4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
